main/urls.py
from django.urls import path, include
import main.views as main
from django.contrib.auth import views as auth_views

app_name = "main"

urlpatterns = [
    path('', main.index, name="index"),
    path('mentions/', main.mentions, name="mentions"),
    path('register/', main.register, name='register'),
    path('accounts/', include('django.contrib.auth.urls')),
    path('password_change/',
        auth_views.PasswordChangeView.as_view(
            template_name='registration/password_change.html',
            success_url='/',
        ),
        name='password_change'
    ),
    path('search_substitute/', main.search_substitutes, name='search_substitutes'),
    path('saved_substitutes/', main.show_saved_substitutes, name='show_saved_substitutes'),
    path('aliment_info/<int:aliment_id>/', main.show_aliment_info, name='show_aliment_info'),
    path('save_substitute/<int:substitute_id>/', main.save_substitute, name='save_substitute'),
    path('delete_substitute/<int:substitute_id>/', main.delete_substitute, name='delete_substitute'),
]

nutella/urls.py
from django.urls import path, include
from django.contrib import admin

urlpatterns = [
    path('', include('main.urls')),
    path('admin/', admin.site.urls),
]

main/models.py
from django.db import models
from django.contrib.auth.models import User

class Category(models.Model):
    name = models.CharField(max_length=128, default=None)
    url = models.CharField(max_length=128, default=None)


class Aliment(models.Model):
    product_name = models.CharField(max_length=128, default=None, unique=True, null=True, blank=True)
    nutrition_grades = models.CharField(max_length=1, default=None, null=True, blank=True)
    stores = models.CharField(max_length=128, default=None, null=True, blank=True)
    image_url = models.CharField(max_length=255, default=None, null=True, blank=True)
    url = models.CharField(max_length=255, default=None, null=True, blank=True)
    category = models.ForeignKey(Category, on_delete=models.CASCADE)

class Substitute(models.Model):
    product_name = models.CharField(max_length=128, default=None, null=True, blank=True)
    nutrition_grades = models.CharField(max_length=1, default=None, null=True, blank=True)
    stores = models.CharField(max_length=128, default=None, null=True, blank=True)
    image_url = models.CharField(max_length=255, default=None, null=True, blank=True)
    url = models.CharField(max_length=255, default=None, null=True, blank=True)
    category = models.ForeignKey(Category, on_delete=models.CASCADE)
    aliment = models.ForeignKey(Aliment, on_delete=models.CASCADE)
    user = models.ForeignKey(User, on_delete=models.CASCADE)

main/views.py
from django.shortcuts import render, redirect
from main.models import Aliment, Substitute
from django.contrib.auth.forms import UserCreationForm
from django.contrib import messages
from django.core.paginator import Paginator

#TODO Tests sur la pagination

def index(request):
    return render(request, 'index.html',)


def mentions(request):
    return render(request, 'mentions.html')


def search_substitutes(request):
    """
    This view gets an aliment name in a post request and renders a list of its substitutes if it finds some,
    redirects to the index if its not a post request
    """
    if request.method == "GET":
        aliment_search = request.GET.get("aliment_search")  # The text searched by the user
        try:
            page = request.GET["page"]
        except:
            page = 1
        if aliment_search:
            aliment = Aliment.objects.filter(product_name__icontains=aliment_search)
        else:
            aliment = None
        substitutes = []
        if aliment:
            aliment = aliment[0]  # If we found at least 1 aliment, put it in the aliment variable
            for i in range(0, 5):
                # get ascii value of A and add the current index to it so we can get the next letters
                nutrition_grade = chr(ord("a") + i)
                # Get the substitutes of the same category and the nutrition grade we're at in the loop
                temp_substitutes = Aliment.objects.filter(category=aliment.category, nutrition_grades=nutrition_grade)
                if temp_substitutes:
                    for substitute in temp_substitutes:
                        substitutes.append(substitute)
                # if the nutrigrade is the same as the aliment's, break
                try:
                    if ord(nutrition_grade) >= ord(aliment.nutrition_grades):
                        break
                except:
                    pass
            if substitutes:
                pages = Paginator(substitutes, 6)
                page_object = pages.get_page(page)
            else:
                page_object = None
            context = {
                'aliment': aliment,
                'aliment_search': aliment_search,
                'substitutes': substitutes,
                'page_object': page_object,
            }
        else:
            context = {
                'aliment': False,
            }
        return render(request, 'aliments.html', context)
    else:
        return redirect("main:index")


def show_aliment_info(request, aliment_id):
    """
    Gets an aliment and renders a page containing its infos

    :param aliment_id: The id of the clicked aliment
    :type aliment_id: int
    """
    context = {}
    if request.method == 'GET':
        context["aliment"] = Aliment.objects.get(id=aliment_id)
        return render(request, "aliment_info.html", context)


def show_saved_substitutes(request):
    """
    Gets the user's saved substitutes and renders a list of them
    """
    context = {}
    if request.user.is_authenticated:
        page = request.GET.get("page", 1)
        context["substitutes"] = Substitute.objects.filter(user=request.user)
        if context["substitutes"]:
            pages = Paginator(context["substitutes"], 6)
            page_object = pages.get_page(page)
        else:
            page_object = None
        context["page_object"] = page_object
        return render(request, 'saved_substitutes.html', context)


def save_substitute(request, substitute_id):
    """
    Saves a substitute in the database.

    :param substitute_id: The id of the aliment we have to save as a substitute
    :type substitute_id: int
    """
    context = {}
    if request.method == 'GET' and request.user.is_authenticated:
        aliment = Aliment.objects.get(id=substitute_id)
        try:
            substitute_data = dict(vars(aliment))  # Get the aliments info as a dict
            try:
                # remove the unnecessary values so we can unpack it into substitutes
                substitute_data.pop('id')
                substitute_data.pop('_state')
            except KeyError:
                pass
            # add some necessary data that aren't in the aliments infos
            substitute_data['aliment'] = aliment
            substitute_data["user"] = request.user
            Substitute.objects.create(**substitute_data)
            context["save_successful"] = True
        except Exception as e:
            context["save_successful"] = False
    return render(request, 'substitute_response.html', context)


def delete_substitute(request, substitute_id):
    """
    Deletes a saved substitute

    :param substitute_id: The id of the substitute we have to delete
    :type substitute_id: int
    """
    if request.user.is_authenticated:
        Substitute.objects.get(id=substitute_id).delete()
        return redirect('main:show_saved_substitutes')


def register(request):
    """
    Registers a user with the data we got in the registration form
    """
    if request.method == 'POST':
        form = UserCreationForm(request.POST)
        if form.is_valid():
            form.save()
            messages.success(request, 'Account created successfully')
            return redirect('main:login')
    else:
        form = UserCreationForm()
    return render(request, 'registration/register.html', {'form': form})

templates/aliment_info.html
{% extends 'index.html' %}

{% block top_div %}
    <script src="https://use.fontawesome.com/ef1bcaa27d.js"></script>
    <div class="col-12">
        <img class="col-4" src="{{ aliment.image_url }}" style="width: 10vw" />
            <h1 class="text-white col-12">{{ aliment.product_name }}</h1>
        <br>
        <hr class="divider">
    </div>
    <div class="col-6">
        <img src="/static/images/nutriscore-{{ aliment.nutrition_grades }}.png">
    </div>
    <div class="col-6">
        {% if aliment.stores %}
            <h3><b>Où l'acheter:</b> {{ aliment.stores }}</h3>
        {% else %}
            <h3><b>Nous n'avons pas pû trouver de magasin vendant ce produit</b></h3>
        {% endif %}
    </div>
    <a href="{{ aliment.url }}" class="btn btn-primary btn-lg" target="_blank">Voir la fiche d'OpenFoodFacts</a>
{% endblock %}

templates/aliments.html
{% extends 'index.html' %}

{% block top_div %}
    <script src="https://use.fontawesome.com/ef1bcaa27d.js"></script>

    {% if not aliment %}
        <h1>Nous n'avons pas pu trouver cet aliment</h1>
    {% endif %}
    {% if aliment and not substitutes %}
        <h1>Nous n'avons pas pu trouver de substitut plus sain à cet aliment</h1>
    {% endif %}
    {% if page_object.has_previous %}
        <div class="position-absolute" style="left: 0">
            <a class="btn btn-primary" href="?page=1&aliment_search={{ aliment_search }}">&laquo; Début</a>
            <a class="btn btn-primary" href="?page={{ page_object.previous_page_number }}&aliment_search={{ aliment_search }}">Précédent</a>
        </div>
    {% endif %}
    {% for substitute in page_object %}
        <div class="col-3 text-center m-1 d-flex bg-gray border-primary aliment">
            <div class="grade_nutritionnel">{{ substitute.nutrition_grades }}</div>
            <div class="text-center col-12" >
                <a href="{% url 'main:show_aliment_info' substitute.id %}">
                    <img class="image d-block m-auto" src="{{ substitute.image_url }}">
                    <h6 class="d-block text-dark aliment_text">{{ substitute.product_name }}</h6>
                </a>
                <a href=" {% url 'main:save_substitute' substitute.id %}"><i class="far fa-save"></i> Sauvegarder</a>
            </div>
        </div>
    {% endfor %}
    {% if page_object.has_next %}
        <div class="position-absolute" style="right: 0">
            <a class="btn btn-primary" href="?page={{ page_object.next_page_number }}&aliment_search={{ aliment_search }}">Suivant</a>
            <a class="btn btn-primary" href="?page={{ page_object.paginator.num_pages }}&aliment_search={{ aliment_search }}">Fin &raquo;</a>
        </div>
    {% endif %}
{% endblock %}

templates/base.html
{% load static %}

<!DOCTYPE html>
<html lang="en">
    <head>
        <meta charset="utf-8" />
        <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no" />
        <meta name="description" content="" />
        <meta name="author" content="" />
        <title>Pur Beurre</title>
        <script src="https://use.fontawesome.com/ef1bcaa27d.js"></script>

        <!-- Favicon-->
        <link rel="icon" type="image/x-icon" href="{% static 'images/favicon.ico' %}" />
        <!-- Font Awesome icons (free version)-->
        <script src="https://use.fontawesome.com/releases/v5.13.0/js/all.js" crossorigin="anonymous"></script>
        <!-- Google fonts-->
        <link href="https://fonts.googleapis.com/css?family=Merriweather+Sans:400,700" rel="stylesheet" />
        <link href="https://fonts.googleapis.com/css?family=Merriweather:400,300,300italic,400italic,700,700italic" rel="stylesheet" type="text/css" />
        <!-- Third party plugin CSS-->
        <link href="https://cdnjs.cloudflare.com/ajax/libs/magnific-popup.js/1.1.0/magnific-popup.min.css" rel="stylesheet" />

        <!-- Core theme CSS (includes Bootstrap)-->
        <link href="{% static "css/styles.css" %}" rel="stylesheet" />
    </head>
    <body id="page-top">
        <!-- Navigation-->
        <nav class="navbar navbar-expand-lg navbar-light fixed-top" id="mainNav">
            <a class="navbar-brand js-scroll-trigger" href="{% url 'main:index' %}"><img class="img-fluid col-3" src="{% static "images/logo_pur_beurre.png" %}">Pur Beurre</a>
            <button class="navbar-toggler navbar-toggler-right" type="button" data-toggle="collapse" data-target="#navbarResponsive" aria-controls="navbarResponsive" aria-expanded="false" aria-label="Toggle navigation"><span class="navbar-toggler-icon"></span></button>
            <div class="collapse navbar-collapse" id="navbarResponsive">
                <ul class="navbar-nav ml-auto my-2 my-lg-0">

                    <li class="nav-item">
                        <form id="search_aliments-top" class="d-inline-flex" action="{% url 'main:search_substitutes' %}" method="get">
                            {% csrf_token %}
                            <input type="text" name="aliment_search" class="form-control inline-block h-100" placeholder="Recherchez un produit ici">
                            <input type="submit" value="Rechercher" class="btn btn-primary align-middle inline-block h-100">
                        </form>
                    </li>
                    <li class="nav-item ml-4"><a href="{% if user.is_authenticated %}{% url 'main:password_change' %}{% else %}{% url 'main:login' %}{% endif %}"><h2><i class="fa fa-user"></i></h2></a></li>
                    {% if user.is_authenticated %}
                        <li class="nav-item ml-4"><a href="{% url 'main:show_saved_substitutes' %}"><h2><i class="fa fa-carrot"></i></h2></a></li>
                        <li class="nav-item ml-4"><a href="{% url 'main:logout' %}"><h2><i class="fa fa-sign-out-alt"></i></h2></a></li>
                    {% endif %}
                </ul>
            </div>
        </nav>
        {% block body %}
        {% endblock %}
        <!-- Footer-->
        <footer class="bg-light py-5">
            <div class="container"><div class="small text-center text-muted"><a href="{% url 'main:mentions' %}">Mentions légales</a></div></div>
            <div class="container"><div class="small text-center text-muted">Copyright © 2020 - Start Bootstrap</div></div>
        </footer>
        <!-- Bootstrap core JS-->
        <script src="https://cdnjs.cloudflare.com/ajax/libs/jquery/3.5.1/jquery.min.js"></script>
        <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.5.0/js/bootstrap.bundle.min.js"></script>
        <!-- Third party plugin JS-->
        <script src="https://cdnjs.cloudflare.com/ajax/libs/jquery-easing/1.4.1/jquery.easing.min.js"></script>
        <script src="https://cdnjs.cloudflare.com/ajax/libs/magnific-popup.js/1.1.0/jquery.magnific-popup.min.js"></script>
        <!-- Core theme JS-->
        <script src="{% static 'js/scripts.js' %}"></script>
    </body>
</html>

templates/index.html
{% extends 'base.html' %}
{% load static %}

{% block body %}
    <!-- Masthead-->
    <header class="masthead">
        <div class="container h-100">
            <div class="row h-100 align-items-center justify-content-center text-center">
                {% block top_div %}
                    <div class="col-lg-10 align-self-end">
                        <h1 class="text-uppercase text-white font-weight-bold">Du gras, oui, mais de qualité !</h1>
                        <hr class="divider my-4" />
                    </div>
                    <div class="col-lg-8 align-self-baseline">
                        <p class="text-white-75 font-weight-light mb-5">Trouvez un produit de substitution pour ceux que vous consommez tous les jours.</p>

                        <form id="search_aliments" action="{% url 'main:search_substitutes' %}" method="get">
                            {% csrf_token %}
                            <input type="text" name="aliment_search" class="col-6 ml-auto mr-auto mb-1 form-control inline-block" placeholder="Recherchez un produit ici">
                            <input type="submit" value="Rechercher" class=" btn btn-primary btn-md align-middle inline-block">
                        </form>
                    </div>
                {% endblock %}
            </div>
        </div>
    </header>
    <!-- Colette et Remy-->
    <section class="page-section" id="services">
        <div class="container">
            <h2 class="text-center mt-0">Colette et Remy</h2>
            <hr class="divider my-4" />
            <div class="row align-items-center justify-content-center">
                <div class="col-4 text-center">
                    <img class="img-fluid" src="{% static "images/ratatouille-portrait.jpg" %}">
                    <div class="text-justify">
                        <p><strong>Remy</strong> : "Pour ma part je me rendais déjà dans bien des magasins car j'aime beaucoup me balader, surtout dans les caves et les cuisines. Je connaissais par coeur le contenu des boutiques bio (dont je raffole) ainsi que les ingrédients de tous les aliments vendus. Lorsque Colette m'a demandé si elle pouvait remplacer son Nutella matinal par un aliment plus sain, je savais tout de suite où le trouver. L'idée de Pur Beurre était née !"</p>
                    </div>
                </div>
                <div class="col-4 text-center">
                    <img class="img-fluid" src="{% static "images/colette-tatou-full.png" %}">
                    <div class="text-justify">
                        <p><strong>Colette Tatou</strong>: "Nous aimons tous manger, surtout en France ! Personnellement, une baguette fraîche, du bon fromage de chèvre et un bon vin rouge me suffisent amplement. Comme tout le monde, je fais mes courses au supermarché. Mais petit à petit je me suis rendue compte, surtout lorsque nous avons ouvert le restaurant, que je pouvais remplacer les produits aseptisés que j'avais l'habitude d'acheter par de bons produits du terroir Et souvent pour le même prix !"</p>
                    </div>
                </div>
            </div>
        </div>
    </section>
    <!-- Contact-->
    <section class="page-section" id="contact">
        <div class="container">
            <div class="row justify-content-center">
                <div class="col-lg-8 text-center">
                    <h2 class="mt-0">Contactez nous!</h2>
                    <hr class="divider my-4" />
                    <p class="text-muted mb-5">Pour toutes questions, n'hésitez pas prendre contact avec nous</p>
                </div>
            </div>
            <div class="row">
                <div class="col-lg-4 ml-auto text-center mb-5 mb-lg-0">
                    <i class="fas fa-phone fa-3x mb-3 text-muted"></i>
                    <div>0123456789</div>
                </div>
                <div class="col-lg-4 mr-auto text-center">
                    <i class="fas fa-envelope fa-3x mb-3 text-muted"></i>
                    <a class="d-block" href="mailto:purbeurre@purbeurre.com">purbeurre@purbeurre.com</a>
                </div>
            </div>
        </div>
    </section>
{% endblock %}

templates/mentions.html
{% extends 'base.html' %}

{% block body %}
    <header class="masthead">
        <div class="container h-100">
            <div class="align-items-center text-center" style="margin-top: 50px;">
                <h5 class="text-center text-white">Mentions légales</h5>
                <hr class="divider my-4">
                <div class="container">

                    <div class="col-lg-12 col-md-12 text-left">
                        <h4 class="text-light">Article 1</h4>
                        <h6 class="text-light">La connexion et la navigation sur le site Pur Beurre par l’Utilisateur
                            implique acceptation intégrale et sans réserve des présentes mentions légales. Ces dernières
                            sont accessibles sur le site à la rubrique « Mentions légales ». </h6>
                        <h4 class="text-light">Article 2</h4>
                        <h6 class="text-light">L'hébergeur du site purbeurre est la Société Heroku.</h6>
                        <h4 class="text-light">Article 3</h4>
                        <h6 class="text-light">Le site est accessible par tout endroit, 7j/7, 24h/24 sauf cas de force
                            majeure, interruption programmée ou non et pouvant découler d’une nécessité de maintenance.
                            En cas de modification, interruption ou suspension des services le site
                            purbeurre ne saurait être tenu responsable. </h6>
                        <h4 class="text-light">Article 4</h4>
                        <h6 class="text-light">Le site assure à l'Utilisateur une collecte et un traitement
                            d'informations personnelles dans le respect de la vie privée conformément à la loi n°78-17
                            du 6 janvier 1978 relative à l'informatique, aux fichiers et aux libertés. En vertu de la
                            loi Informatique et Libertés, en date du 6 janvier 1978, l'Utilisateur dispose d'un droit
                            d'accès, de rectification, de suppression et d'opposition de ses données personnelles.
                            L'Utilisateur peut exercer ce droit par mail à l'adresse : purbeurre@purbeurre.com </h6>
                        <h4 class="text-light">Article 5</h4>
                        <h6 class="text-light">L’Utilisateur est informé que lors de ses visites sur le site, un cookie
                            peut s’installer automatiquement sur son logiciel de navigation. En naviguant sur le site,
                            il les accepte. Un cookie est un élément qui ne permet pas d’identifier l’Utilisateur mais
                            sert à enregistrer des informations relatives à la navigation de celui-ci sur le site
                            Internet. L’Utilisateur pourra désactiver ce cookie par l’intermédiaire des paramètres
                            figurant au sein de son logiciel de navigation. </h6>
                    </div>

                </div>
            </div>
        </div>
    </header>
{% endblock %}

templates/saved_substitutes.html
{% extends 'index.html' %}

{% block top_div %}
    <script src="https://use.fontawesome.com/ef1bcaa27d.js"></script>

    {% if not substitutes %}
        <h1>Nous n'avons pas pu trouver de substituts sauvegardés dans votre compte</h1>
        {% else %}
        {% if page_object.has_previous %}
        <div class="position-absolute" style="left: 0">
            <a class="btn btn-primary" href="?page=1">&laquo; Début</a>
            <a class="btn btn-primary" href="?page={{ page_object.previous_page_number }}">Précédent</a>
        </div>
        {% endif %}
        {% for substitute in page_object %}
            <div class="col-3 text-center m-1 d-flex bg-gray border-primary aliment">
                <div class="text-center col-12" >
                    <img class="image d-block m-auto" src="{{ substitute.image_url }}">
                    <h6 class="d-block text-dark aliment_text">{{ substitute.product_name }}</h6>
                    <a href="{% url 'main:delete_substitute' substitute.id %}"><i class="fa fa-trash"></i> Supprimer</a>
                </div>
            </div>
        {% endfor %}
        {% if page_object.has_next %}
        <div class="position-absolute" style="right: 0">
            <a class="btn btn-primary" href="?page={{ page_object.next_page_number }}">Suivant</a>
            <a class="btn btn-primary" href="?page={{ page_object.paginator.num_pages }}">Fin &raquo;</a>
        </div>
        {% endif %}
    {% endif %}
{% endblock %}

templates/substitute_response.html
{% extends 'index.html' %}

{% block top_div %}
    {% if save_successful %}
        <h1>Votre substitut a bien été sauvegardé</h1>
    {% else %}
        <h1>Il y a eu une erreur a la sauvegarde de votre substitut</h1>
    {% endif %}
{% endblock %}